name: tepi_trade CI
on:
  workflow_dispatch:
  push:
    branches: [principal, main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requisitos.txt ]; then pip install -r requisitos.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Executar migração WooCommerce
        env:
          WC_URL: ${{ secrets.WC_URL }}
          WC_CK: ${{ secrets.WC_CK }}
          WC_CS: ${{ secrets.WC_CS }}
          CSV_URL: ${{ secrets.CSV_URL }}
        run: |
          python migrate_wc.py
